/*
================================================================================
 kawayan - Unified Database Deploy Script (PostgreSQL)
================================================================================
 (Brand: kaw.a.yan — Baybayin ᜃᜏ᜔.ᜀᜌ᜔.ᜀᜈ᜔; backend identifiers: kawayan)

 Purpose   : Apply EF schema + seed data to PostgreSQL (idempotent / safe to re-run)
 Database  : PostgreSQL 16+ (matches InitialPostgres migration)
 Migration : 20260524042919_InitialPostgres

 Usage     :
   psql "postgresql://user:pass@host:5432/dbname" -f database/deploy.sql
   Railway → connect to Postgres service → Query tab → paste/run

 Regenerate schema block:
   dotnet ef migrations script --idempotent -p src/kawayan.API -o database/_schema.postgresql.sql

 Legacy SQL Server script: database/deploy.sqlserver.sql
================================================================================
*/

/* =============================================================================
   STEP 1 - EF Core schema (Initialising InitialPostgres)
   ============================================================================= */

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "Articles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Slug" text NOT NULL,
        "Description" text NOT NULL,
        "Content" text NOT NULL,
        "ImageUrl" text,
        "ImageDescription" text NOT NULL,
        "AuthorFullName" text NOT NULL,
        "IsPublished" boolean NOT NULL,
        "PublishedAt" timestamp without time zone,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Articles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "CompanyDetails" (
        "Id" integer NOT NULL,
        "NameMain" text NOT NULL,
        "NameBaybayin" text NOT NULL,
        "Tagline" text NOT NULL,
        "LogoUrl" text,
        "PrimaryColor" text NOT NULL,
        "Email" text NOT NULL,
        "Phone" text NOT NULL,
        "Street" text NOT NULL,
        "Barangay" text NOT NULL,
        "City" text NOT NULL,
        "Province" text NOT NULL,
        "Region" text NOT NULL,
        "Country" text NOT NULL,
        "PostalCode" text NOT NULL,
        "Latitude" numeric(9,6),
        "Longitude" numeric(9,6),
        "Website" text NOT NULL,
        "SocialLinksJson" text NOT NULL,
        "CoverImageUrl" text,
        "AboutImageUrl" text,
        "EstablishedYear" integer,
        "ShortDescription" text NOT NULL,
        "FullDescription" text NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_CompanyDetails" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "Inquiries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SenderName" text NOT NULL,
        "SenderEmail" text NOT NULL,
        "Phone" text NOT NULL,
        "Subject" text NOT NULL,
        "Message" text NOT NULL,
        "IsRead" boolean NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Inquiries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "LegalPages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Slug" text NOT NULL,
        "Title" text NOT NULL,
        "Body" text NOT NULL,
        "LastRevised" date,
        "IsPublished" boolean NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_LegalPages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "MediaFiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileName" text NOT NULL,
        "Url" text NOT NULL,
        "UploadedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_MediaFiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "PageSections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Page" text NOT NULL,
        "SectionKey" text NOT NULL,
        "ContentJson" text NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_PageSections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "Services" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Price" numeric,
        "IconUrl" text,
        "ImageUrl" text,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "DisplayName" text NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "RolePermissions" (
        "RoleId" integer NOT NULL,
        "Permission" text NOT NULL,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "Permission"),
        CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" text NOT NULL,
        "ExpiresAt" timestamp without time zone NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE TABLE "UserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Articles_Slug" ON "Articles" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_LegalPages_Slug" ON "LegalPages" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_PageSections_Page_SectionKey" ON "PageSections" ("Page", "SectionKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524042919_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524042919_InitialPostgres', '9.0.4');
    END IF;
END $EF$;

COMMIT;

/* =============================================================================
   STEP 2 - Reference seed data (idempotent)
   ============================================================================= */

-- Company profile (Id = 1)
INSERT INTO "CompanyDetails" (
    "Id", "NameMain", "NameBaybayin", "Tagline", "LogoUrl", "PrimaryColor", "Email", "Phone",
    "Street", "Barangay", "City", "Province", "Region", "Country", "PostalCode",
    "Latitude", "Longitude", "Website", "SocialLinksJson",
    "CoverImageUrl", "AboutImageUrl", "EstablishedYear",
    "ShortDescription", "FullDescription", "UpdatedAt"
)
SELECT
    1,
    'kaw.a.yan',
    'ᜃᜏ᜔.ᜀᜌ᜔.ᜀᜈ᜔',
    'Sustainable. Strong. Natural.',
    NULL,
    '#4A7C59',
    'hello@kawayan.com',
    '+63 912 345 6789',
    '123 Bamboo Road',
    '',
    'Cagayan de Oro',
    'Misamis Oriental',
    'Northern Mindanao',
    'Philippines',
    '9000',
    8.484722,
    124.647222,
    'https://kawayan.com',
    '{"facebook":"https://facebook.com/kawayan","instagram":"https://instagram.com/kawayan"}',
    'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1600&h=900&fit=crop',
    'https://images.unsplash.com/photo-1598900384379-02b0883e4952?w=800&h=600&fit=crop',
    2010,
    'kaw.a.yan — premium bamboo products and raw materials for construction, furniture, crafts, and agriculture — delivered across the region.',
    'kaw.a.yan (kawayan) has been supplying high-quality bamboo to businesses and individuals since 2010. We work directly with local bamboo farmers to ensure sustainable harvesting practices, consistent quality, and fair pricing. Our product range covers raw bamboo poles, treated lumber, woven panels, and custom cuts for any project size.',
    (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "CompanyDetails" WHERE "Id" = 1);

-- Services catalog
INSERT INTO "Services" ("Title", "Description", "IconUrl", "ImageUrl")
SELECT v."Title", v."Description", v."IconUrl", v."ImageUrl"
FROM (VALUES
    ('Raw Bamboo Poles', 'Available in various lengths (3m, 6m, 9m) and diameters. Suitable for construction, scaffolding, garden structures, and fencing. Sold per pole or in bulk.', NULL, 'https://images.unsplash.com/photo-1598900384379-02b0883e4952?w=600&h=400&fit=crop'),
    ('Treated Bamboo Lumber', 'Kiln-dried and pressure-treated for extended lifespan. Resistant to insects, moisture, and warping. Ideal for flooring, decking, and structural framing.', NULL, 'https://images.unsplash.com/photo-1501004318641-b39e0a090e8e?w=600&h=400&fit=crop'),
    ('Woven Bamboo Panels', 'Hand-woven panels in various weave patterns. Used for interior walls, ceilings, furniture backing, and decorative partitions. Natural and stained finishes available.', NULL, 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=600&h=400&fit=crop'),
    ('Bamboo Stakes & Garden Poles', 'Thin, lightweight poles for plant support, trellises, and agricultural use. Available in bundles of 50 or 100.', NULL, 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop'),
    ('Bulk & Wholesale Supply', 'Volume pricing for contractors, furniture manufacturers, and exporters. Minimum order quantities apply. Contact us for a custom quote.', NULL, 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&h=400&fit=crop'),
    ('Custom Cut Orders', 'Need a non-standard size or a specific treatment? We accept custom orders with a 5-7 business day lead time.', NULL, 'https://images.unsplash.com/photo-1503387763038-714adcc6aa3d?w=600&h=400&fit=crop')
) AS v("Title", "Description", "IconUrl", "ImageUrl")
WHERE NOT EXISTS (SELECT 1 FROM "Services");

-- Administrator (password: Admin123!)
DO $$
DECLARE
    admin_role_id integer;
    admin_user_id integer;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "Users") THEN
        INSERT INTO "Roles" ("Name") VALUES ('Administrator')
        RETURNING "Id" INTO admin_role_id;

        INSERT INTO "RolePermissions" ("RoleId", "Permission") VALUES
            (admin_role_id, 'content.manage'),
            (admin_role_id, 'media.manage');

        INSERT INTO "Users" ("Email", "PasswordHash", "DisplayName", "IsActive")
        VALUES (
            'admin@kawayan.com',
            '$2a$11$cwABrJoUwTw/ZfsjXdhUJeaMJknwJQ20/0qe.sGCbi4sN6FW872he',
            'Administrator',
            true
        )
        RETURNING "Id" INTO admin_user_id;

        INSERT INTO "UserRoles" ("UserId", "RoleId")
        VALUES (admin_user_id, admin_role_id);
    END IF;
END $$;

DELETE FROM "RolePermissions" WHERE "Permission" = 'settings.manage';

/* =============================================================================
   STEP 3 - Public content seed (legal pages, page sections, articles)
   ============================================================================= */

INSERT INTO "LegalPages" ("Slug", "Title", "Body", "LastRevised", "IsPublished", "UpdatedAt")
SELECT 'privacy-policy', 'Privacy Policy',
    'This Privacy Policy describes how {{company_name}} ("we", "us") collects, uses, and protects personal information when you visit our website or contact us.'
    || E'\n\nInformation we collect: name, email, phone, and messages sent through our contact form; basic technical data in server logs.'
    || E'\n\nHow we use information: to respond to inquiries, deliver services, improve our website, and meet legal obligations. We do not sell your personal information.'
    || E'\n\nCookies: we use essential cookies for site operation. If analytics are enabled later, this policy will be updated.'
    || E'\n\nYour rights: contact us through the email on our Contact page to request access, correction, or deletion of your data.',
    CURRENT_DATE, true, (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "LegalPages" WHERE "Slug" = 'privacy-policy');

INSERT INTO "LegalPages" ("Slug", "Title", "Body", "LastRevised", "IsPublished", "UpdatedAt")
SELECT 'terms', 'Terms of Service',
    'These Terms of Service govern your use of the {{company_name}} website. By accessing this site, you agree to these terms.'
    || E'\n\nUse of the website: browse for lawful purposes only. Do not disrupt the site, scrape content without permission, or harm other users.'
    || E'\n\nInformation on this site is general. Product descriptions, pricing, and availability may change. Nothing here is a binding offer until confirmed in writing by {{company_name}}.'
    || E'\n\nIntellectual property: materials on this site are owned by {{company_name}} or used with permission. Do not copy or redistribute without prior written consent.'
    || E'\n\nLimitation of liability: to the fullest extent permitted by law, {{company_name}} is not liable for indirect or consequential damages from your use of this website.'
    || E'\n\nGoverning law: the laws of the Philippines unless otherwise required. We may update these terms; continued use after changes means acceptance.',
    CURRENT_DATE, true, (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "LegalPages" WHERE "Slug" = 'terms');

INSERT INTO "LegalPages" ("Slug", "Title", "Body", "LastRevised", "IsPublished", "UpdatedAt")
SELECT 'cookie-policy', 'Cookie Policy',
    'This Cookie Policy explains how {{company_name}} uses cookies and similar technologies on our website.'
    || E'\n\nCookies are small text files stored on your device. They help remember preferences and understand how visitors use pages.'
    || E'\n\nEssential cookies are required for basic operation (for example admin sign-in and security). Analytics cookies are only used if our team enables them.'
    || E'\n\nYou can control cookies in your browser. Disabling essential cookies may affect how parts of the site work.'
    || E'\n\nWe may update this policy when our tools change. Questions: use the contact details on our Contact page.',
    CURRENT_DATE, true, (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "LegalPages" WHERE "Slug" = 'cookie-policy');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'hero', '{"subtext":"Premium bamboo poles, lumber, and woven materials sourced with care across Mindanao.","ctaPrimary":"View Services","ctaPrimaryLink":"/services","ctaSecondary":"Contact Us","ctaSecondaryLink":"/contact"}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'hero');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'whyChooseUs', '{"cards":[{"icon":"🌿","title":"Farm-direct quality","body":"We coordinate with local growers so poles meet consistent diameter and moisture checks before dispatch."},{"icon":"🪵","title":"Treatment options","body":"Ask for treatment suited to humidity, insects, and load so your build lasts in tropical conditions."},{"icon":"📦","title":"Retail to wholesale","body":"From bundled garden stakes to truckload jobs for contractors, we align cuts and logistics to your timeline."}]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'whyChooseUs');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'missionVision', '{"mission":"Supply responsible, high-quality bamboo materials that help builders, furniture makers, and growers succeed.","vision":"Be a trusted Mindanao partner for sustainable bamboo—growing with our partners and the landscapes we depend on."}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'missionVision');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'stats', '{"items":[{"value":"14+","label":"Years in business"},{"value":"500K+","label":"Poles supplied"},{"value":"180+","label":"Partner outlets"},{"value":"24/7","label":"Inquiry line"}]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'stats');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'testimonials', '{"items":[{"quote":"Treated poles for our resort cabanas arrived on schedule and passed our engineer inspection.","name":"Dennis V.","role":"Project Manager, Bukidnon"},{"quote":"We order woven panels monthly for export crates; kaw.a.yan keeps weave density consistent batch to batch.","name":"Rina L.","role":"Operations, Cagayan de Oro"},{"quote":"Wholesale pricing and straight answers on lead times—finally a supplier that matches how we bid jobs.","name":"Noel K.","role":"Contractor, Misamis Oriental"}]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'testimonials');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'home', 'cta', '{"headline":"Planning a build or production run?","subtext":"Share pole lengths, treatment, and delivery window—we will prepare a quote.","buttonText":"Contact us","buttonLink":"/contact"}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'home' AND "SectionKey" = 'cta');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'about', 'hero', '{"headline":"About kaw.a.yan","subtext":"Bamboo specialists in Cagayan de Oro serving builders, furniture makers, and agricultural partners."}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'about' AND "SectionKey" = 'hero');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'about', 'story', '{"paragraphs":["kaw.a.yan started as a small yard serving local contractors who needed dependable pole sizes and honest moisture readings.","Today we still visit farms with our own checks, expand treatment and cut options, and keep digital records so repeat customers get the same spec every order.","Whether you are prototyping furniture or fencing a plantation, we aim to be the team you call first for bamboo in Northern Mindanao."]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'about' AND "SectionKey" = 'story');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'about', 'missionVision', '{"mission":"Supply responsible, high-quality bamboo materials that help builders, furniture makers, and growers succeed.","vision":"Be a trusted Mindanao partner for sustainable bamboo—growing with our partners and the landscapes we depend on."}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'about' AND "SectionKey" = 'missionVision');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'about', 'values', '{"cards":[{"icon":"🌱","title":"Stewardship","body":"We favor harvest cycles and partners who protect clumps for the next season."},{"icon":"📏","title":"Precision","body":"Measured diameters, straight cuts, and clear labels reduce waste on your site."},{"icon":"🤝","title":"Fair dealing","body":"Quotes spell out grades and treatments—no surprise substitutions."},{"icon":"⚡","title":"Responsiveness","body":"Sales and logistics pick up the phone because timelines drive your cash flow."}]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'about' AND "SectionKey" = 'values');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'about', 'team', '{"members":[{"initials":"MR","name":"Mara Ramos","role":"Managing Director","bio":"Sets sourcing standards and works with farm cooperatives on long-term supply."},{"initials":"JP","name":"Jon Paredes","role":"Yard & Treatment Lead","bio":"Runs drying, pressure treatment batches, and final QC before trucks roll out."},{"initials":"AL","name":"Ana Lim","role":"Customer Success","bio":"Coordinates quotes, cut lists, and delivery windows for contractors and exporters."}]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'about' AND "SectionKey" = 'team');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'services', 'hero', '{"headline":"What we supply","subtext":"Raw poles, treated lumber, woven panels, and custom cuts for construction, furniture, crafts, and farms."}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'services' AND "SectionKey" = 'hero');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'services', 'cta', '{"headline":"Need a volume quote?","subtext":"Send specs and we will match grade, treatment, and logistics to your project.","buttonText":"Contact us","buttonLink":"/contact"}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'services' AND "SectionKey" = 'cta');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'contact', 'hero', '{"headline":"Get in touch","subtext":"Quotes, site visits, and pickup windows—tell us what you need."}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'contact' AND "SectionKey" = 'hero');

INSERT INTO "PageSections" ("Page", "SectionKey", "ContentJson", "UpdatedAt")
SELECT 'contact', 'details', '{"hours":["Monday – Friday: 8:00 AM – 6:00 PM","Saturday: 8:00 AM – 12:00 PM","Sunday: Closed"]}', (NOW() AT TIME ZONE 'UTC')
WHERE NOT EXISTS (SELECT 1 FROM "PageSections" WHERE "Page" = 'contact' AND "SectionKey" = 'details');

INSERT INTO "Articles" ("Title", "Slug", "Description", "Content", "ImageUrl", "IsPublished", "PublishedAt", "CreatedAt", "UpdatedAt", "AuthorFullName", "ImageDescription")
SELECT
    'Choosing bamboo poles for tropical builds',
    'choosing-bamboo-poles-for-builds',
    'Diameter, age class, and moisture checks that save rework on site.',
    'Bamboo looks simple until you load it. Start with the structural chart from your engineer, then match pole class to span and connector detail.'
    || E'\n\nOn receipt, skim for cracks at nodes, spiral shakes, and bore holes. A quick moisture spot-check helps you decide whether to acclimatize before install.'
    || E'\n\nWhen in doubt, step up one diameter class or specify treated stock for ground contact and wet rooms.',
    'https://images.unsplash.com/photo-1598900384379-02b0883e4952?w=1200&h=750&fit=crop',
    true, (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'),
    'Mara Ramos', 'Fresh-cut bamboo poles stacked at a supplier yard.'
WHERE NOT EXISTS (SELECT 1 FROM "Articles" WHERE "Slug" = 'choosing-bamboo-poles-for-builds');

INSERT INTO "Articles" ("Title", "Slug", "Description", "Content", "ImageUrl", "IsPublished", "PublishedAt", "CreatedAt", "UpdatedAt", "AuthorFullName", "ImageDescription")
SELECT
    'Treatment options for longer-lasting bamboo',
    'treatment-options-for-longer-life',
    'How boron, pressure cycles, and drying targets extend service life in humid climates.',
    'Treatment is not cosmetic—it moves the failure curve. Boron-based systems target starch-loving pests; pressure helps chemistry reach the inner wall.'
    || E'\n\nPair treatment with a drying target suited to your end use: furniture wants stability, outdoor structures want a buffer against rain cycles.'
    || E'\n\nAsk your supplier for batch records so you can align warranty and maintenance plans with what actually entered the cylinder.',
    'https://images.unsplash.com/photo-1501004318641-b39e0a090e8e?w=1200&h=750&fit=crop',
    true, (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'),
    'Jon Paredes', 'Planed bamboo strips suitable for interior use after treatment.'
WHERE NOT EXISTS (SELECT 1 FROM "Articles" WHERE "Slug" = 'treatment-options-for-longer-life');

INSERT INTO "Articles" ("Title", "Slug", "Description", "Content", "ImageUrl", "IsPublished", "PublishedAt", "CreatedAt", "UpdatedAt", "AuthorFullName", "ImageDescription")
SELECT
    'Woven panels: pattern, backing, and install tips',
    'woven-panels-for-interiors',
    'What architects ask before specifying woven bamboo for ceilings and partitions.',
    'Weave pattern drives shadow lines and acoustic behavior. Tighter weaves read more formal; open weaves feel casual but need backing for privacy.'
    || E'\n\nSubstrate movement is the usual callback issue—use clips or slotted channels where seasons swing humidity hard.'
    || E'\n\nOrder a sample tile early; color shifts between batches are natural with plant fibers.',
    'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1200&h=750&fit=crop',
    true, (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'),
    'Ana Lim', 'Bamboo canes and woven textures in natural light.'
WHERE NOT EXISTS (SELECT 1 FROM "Articles" WHERE "Slug" = 'woven-panels-for-interiors');

INSERT INTO "Articles" ("Title", "Slug", "Description", "Content", "ImageUrl", "IsPublished", "PublishedAt", "CreatedAt", "UpdatedAt", "AuthorFullName", "ImageDescription")
SELECT
    'Wholesale checklist for first-time bamboo buyers',
    'wholesale-checklist-for-buyers',
    'Lead times, MOQs, and documents that keep container and loose-truck orders smooth.',
    'Confirm incoterms, strapping style, and fumigation certificates before you lock vessel space.'
    || E'\n\nShare a pack list with net and gross weights; yards photograph loads so both sides agree on bundle counts at gate-out.'
    || E'\n\nIf you blend SKUs, ask for segregation maps so receivers can put stock away without reshuffling.',
    'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&h=750&fit=crop',
    true, (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'), (NOW() AT TIME ZONE 'UTC'),
    'Mara Ramos', 'Warehouse aisle with bundled construction materials.'
WHERE NOT EXISTS (SELECT 1 FROM "Articles" WHERE "Slug" = 'wholesale-checklist-for-buyers');

DO $$ BEGIN RAISE NOTICE 'kawayan database deploy completed.'; END $$;
